name: Subway
main: me.Fahlur.Subway.Subway
version: 3.0
author: Purely Satanic
depend: [WorldGuard]
description: >
             SubwaySystem by Purely Satanic, Rebuilt by Fahlur
commands:
  Subway:
    description:
    usage: |
      /<command> generate [radius] [schematic] [-e]
      /<command> custom [name] [schematic]
      /<command> remove [station]
      /<command> search [region]
